### ISSUE TITLE
[Sky Q Box] Failed to turn on Sky Q Box. ECONNTIMEOUT: connect timeout 192.168.0.2:5900

### ISSUE THREAD

**Issue by neiloakley** [AdamSwinden/homebridge-sky-q#2]
[2017-12-11 07:43:38] Homebridge is running on port 51826.
[2017-12-11 07:43:38] [SmartThings] Direct Connect Is Listening On 192.168.0.6:8050
[2017-12-11 07:43:39] [SmartThings] SmartThings Hub Communication Established
[2017-12-11 07:44:25] [Sky Q Box] Sending on command to 'Sky Q Box'...
[2017-12-11 07:44:26] [Sky Q Box] Failed to turn on Sky Q Box. ECONNTIMEOUT: connect timeout 192.168.0.2:5900
[2017-12-11 07:44:28] [Sky Q Box] Sending on command to 'Sky Q Box'...
[2017-12-11 07:44:29] [Sky Q Box] Failed to turn on Sky Q Box. ECONNTIMEOUT: connect timeout 192.168.0.2:5900
[2017-12-11 07:44:46] [Sky Q Box] Failed to turn on Sky Q Box. Error: connect ETIMEDOUT 192.168.0.2:5900
C:\Users\Neil Oakley\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\util\once.js:12
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at C:\Users\Neil Oakley\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\util\once.js:12:13
    at C:\Users\Neil Oakley\AppData\Roaming\npm\node_modules\homebridge-sky-q\index.js:41:4
    at C:\Users\Neil Oakley\AppData\Roaming\npm\node_modules\homebridge-sky-q\node_modules\sky-remote\sky-remote.js:60:6
    at Socket.<anonymous> (C:\Users\Neil Oakley\AppData\Roaming\npm\node_modules\homebridge-sky-q\node_modules\sky-remote\sky-remote.js:36:4
)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

C:\Users\Neil Oakley\homebridge>

**Comment by rhyssmith** [comment]
Same here,
```
homebridge > [07/02/2018, 22:15:16] [Sky Q Box] Sending on command to 'Sky Q Box'... 
homebridge > [07/02/2018, 22:15:17] [Sky Q Box] Failed to turn on Sky Q Box. ECONNTIMEOUT: connect timeout 10.0.11.70:5900
```

TCP:5900 isn't open on the Sky Q box, which is why it can't connect to it I guess!

**Comment by obarber** [comment]
I'm also having this problem, tried port forwarding on 5900 on TCP but still I get the same error message.

**Comment by neiloakley** [comment]
I cant see in the code where the port to call is set. Any ideas?

**Comment by neiloakley** [comment]
Just found this:

https://github.com/dalhundal/sky-remote/issues/11

Looks like commands need to go to port 49160

**Comment by obarber** [comment]
I can’t find it either. It must set it automatically

**Comment by neiloakley** [comment]
Looks like in the .js it has a dependency on   "dependencies": {    "sky-remote": "^1.1.0" },

And in sky-remote.ks a variable for the port is set:
		var client = net.connect({
			host: host,
			port: port || 49160
		});

So i'm going to try installing sky-remote https://github.com/dalhundal/sky-remote and then run this again.

**Comment by obarber** [comment]
Please update me with how it goes for you. I’d love to be able to get this to work...

Thanks mate!

**Comment by neiloakley** [comment]
I've submitted a pull request to sky-remote, I need that to be merged and then hopefully reinstalling sky-remote and rebooting homebridge should be all thats needed. 

https://github.com/dalhundal/sky-remote/issues/11#issuecomment-349632116

**Comment by jdebardi** [comment]
Your PR will not be approved as it is not the correct solution!!! Read my original comments on the issue you referenced to understand why.
You just need to have Homebridge NOT use the sky_q switch when calling sky-remote. No code changes are needed in sky-remote are needed at all.

**Comment by jdebardi** [comment]
To be explicit, you need a PR on this project for;
-var remoteControl = new SkyRemote(config.ipAddress, SkyRemote.SKY_Q);
+var remoteControl = new SkyRemote(config.ipAddress);

**Comment by neiloakley** [comment]
Thanks for your help. You mention the Fox was needed on this project (homebridge-Sky-q) but you also submitted a PR on sky-remote. So is there still a change needed to this project?

**Comment by jdebardi** [comment]
Sky updated their firmware to change the port between versions - the proper solution for boxes running the new firmware is per my comment above. 
However, there are of course other people using sky-remote who don't want the rug pulled out from under them, so I submitted a change to allow a 'legacy option' only applicable to people running old Sky Q firmware (which in theory is no one, but just in case).
With the change I suggest here, you can run the sky-remote code with or without my submitted changes there.

**Comment by neiloakley** [comment]
Could you submit the PR? I'm very new to all this. 

I just want homebridge to work with my Sky Q box. I never installed sky-remote, only homebridge-sky-q and homebridge

**Comment by jdebardi** [comment]
I'm in the process of setting up Homebridge (having discovered it via your comments - thanks!). I'll submit the PR once I have something I can test on (hopefully this evening) 👍

**Comment by jdebardi** [comment]
OK, it took all of 2 mins to install and fix! PR submitted
Now I have the fork of code I'm going to expand on this project as well as there is no status feedback at the moment.
I actually have already written my own complete web based Sky Q remote based on the same sky-remote back end as this project, so will be easy for me to make this Homebridge-plugin MUCH more useful :)

**Comment by neiloakley** [comment]
Excellent - I also got mine working just by using your comment above and editing the local package on my PC in the folder I run homebridge from. 

Forgive the stupid question, but if you fork from the master, how to I install your version of homebridge-sky-q rather than this version?

**Comment by obarber** [comment]
Do either of you have an easy way to set this up? As I still don't understand. Today, I set homebridge up for my brother at his house, and added his Sky Q box, and it worked straight away on the port it was set to. His sky box is on the latest firmware also.

**Comment by jdebardi** [comment]
obarber- if you did it today, you’d have got the new version I submitted of sky-remote which has backwards compatibility for the now ‘incorrect’ way This Homebridge plugin works.

neiloakley - I plan to PR my changes back to this (assuming the original author of this project like my updates). But you can get to my fork from the forks button above and just manually edit the .js files to match my upcoming changes (as you already did). It’s a bit of a hack but would work.
If the original author doesn’t like my updates I’ll release my own sky-q plugin which you would be able to use instead.

**Comment by neiloakley** [comment]
Good stuff - PLEASE PLEASE PLEASE keep me posted :)

And if you need testers, let me know. I pick things up fairly quickly so may be of help.

**Comment by obarber** [comment]
Jdebardi - I just clicked on your profile and downloaded your new code, worked a treat first time for both my Sky Q and Q Mini boxes. 

Thanks a lot for your help, and I apologise for not realising.

Now if you'd have the expertise to create a switch for the Xbox One, because the current one only supports switching on capability, not switching off.

Once again, thank you so much.

**Comment by jdebardi** [comment]
@neiloakley feel free to try my latest update per #1 
FYI - you will have to manually install the 'sky-q' package via npm, and manually update the code from my fork of course.

**Comment by obarber** [comment]
Jdebardi - is it just as simple as downloading/installing the same sky-q file I did last night, and it will update it to the newest version with the state awareness

**Comment by jdebardi** [comment]
There is a new dependancy, so install it via "sudo npm install -g sky-q", then copy my code again as you did before and you should be good.

**Comment by obarber** [comment]
I have just installed it using "sudo npm etc." and copied the code for the config file again, put my IPs in again, it works, but the state awareness isn't working for me. Is it something that I'm doing wrong?

**Comment by jdebardi** [comment]
So from my fork you have overwritten this file?
/usr/lib/node_modules/homebridge-sky-q/index.js

In the Homebridge logs when you open the Home app (or switch the box on/off via the app) you should see one of these prints, depending on if the Sky box is off or on at the time;
Feb 12 12:11:48 jose-stick homebridge[2489]: [2018-2-12 12:11:48] [Sky Q Box] Sky Q Box is in standby :-(
Feb 12 15:06:25 jose-stick homebridge[2489]: [2018-2-12 15:06:25] [Sky Q Box] Sky Q Box is on :-)

**Comment by obarber** [comment]
My apologies, I hadn't updated the index.js file. I now have and it works perfectly. I have received both commands from both my Sky Q boxes: 

[2018-2-12 16:02:01] [Sky Q Box] Sky Q Box is on :-)
[2018-2-12 16:02:01] [Sky Q Mini] Sky Q Mini is on :-)

Thank you so much! Thank you also for your help and patience with me setting mine up.

Are you trying to add any other features to it, or is this about the limit of what can be done?

**Comment by jdebardi** [comment]
I'm considering additional features like shortcut buttons to favourite channels, or indeed opening it to allow any combination of buttons (rather than the single hard coded 'power') as of now. Just exploring the HomeKit/Homebridge abilities at the moment!

**Comment by obarber** [comment]
That'd be very interesting. I'd like to try out features early if you ever need anyone. Is there no set commands to add to the code (like "power" is) to make it easy?

Also I'm unsure if you saw my earlier comment about creating a plugin for the Xbox One. As I said, I'm not sure how familiar you are with the platform, but the current one only allows power on, not power off. That would be so handy!

Thanks so much.

**Comment by jdebardi** [comment]
See here for list of available commands https://github.com/dalhundal/sky-remote
Exposing them will be very easy - just need to make it sensibly configurable in Homebridge/HomeKit - a toggle switch to a favourite channel is silly - need a push button...

As for the Xbox One off, I did look into it. Problem is, on is a single packet to send to wake it up, off is an encrypted packet sent via your Microsoft account. So while possible, would be very hard work to backwards engineer the protocol to MS. The other options is, if you have a Windows PC which is always on, and can find a way to script it to send the command (as it already has your MS account/Cortana etc), then Homebridge could relatively easily be made to call that script on the Windows machine. I don't have a Windows PC or an Xbox though so that's as far as I can go!

**Comment by obarber** [comment]
Well I greatly appreciate you looking into the Xbox feature anyway!

I have another request, I have basically added everything I can, except my living room TV. It is an LG Smart TV, but I haven't been able to find any plugins for that. It is connected to the internet so has an IP to control it. Would you have any idea on how to code a plugin to just turn this on and off?

**Comment by jdebardi** [comment]
None of these work for your LG? https://www.npmjs.com/package/homebridge-lgtv2 https://www.npmjs.com/package/homebridge-lgtv-2012 https://www.npmjs.com/package/homebridge-webos2

**Comment by rhyssmith** [comment]
Will have a look at the updated sky-q stuff this evening, thanks for your work on fixing this everyone!

@obarber I'm using https://github.com/merdok/homebridge-webos3 with my LG OLED55B7V

**Comment by obarber** [comment]
For some reason, I keep getting the error: 

[2018-2-12 16:52:45] [My webOS tv] webOS3 error Error: connect ECONNREFUSED 192.168.0.29:3000... 

Looks like another port issue possibly.

My TV is the LG LT40C860.

**Comment by jdebardi** [comment]
Save continuing to clutter this issue up, I've made an Issue on my fork for the development of my suggested feature here https://github.com/jdebardi/homebridge-sky-q/issues/2

Please continue chat on that thread 👍

**Comment by jdebardi** [comment]
Hi all - just to say I've added LOTS of features in my branch. @obarber is already having a play with them. Be great if some of you could also have a go for testing before I submit to merge on this master project. https://github.com/jdebardi/homebridge-sky-q/blob/Any-Cmd/README.md
Many thanks.

**Comment by Mathy5** [comment]
Unfortunately still got the problem: " Failed to turn on Sky Q Box. Error: getaddrinfo ENOTFOUND " is there still a way to control my sky Q box with homebridge?

Many thanks.

**Comment by jdebardi** [comment]
@Mathy5 It’s working fine for me still. I use it every day on my Silver and Mini boxes.

**Comment by Mathy5** [comment]
@jdebardi maybe is because I have Sky Q platinum and not the silver?

**Comment by jdebardi** [comment]
Platinum is the same as Silver; just branding name
Do you definitely have the latest versions of the homebridge plugin installed?

**Comment by Mathy5** [comment]
Yes! it's the last one! but making an `npm outdated` i see this: 

![p](https://user-images.githubusercontent.com/35546499/44774123-93420900-ab72-11e8-9158-174c6eebb4a3.jpeg)

**Comment by jdebardi** [comment]
Looking into that error, it would suggest your IP address is not correct for the box.
What do you see if you do from your home bridge server;
curl http://<sky_box_ip>:9006/as/system/information

It should look like;

> jose@jose-stick:~$ curl http://10.11.12.87:9006/as/system/information
{
   "ASVersion" : "Q071.000.29.00-AS_asdev",
   "DRMActivationStatus" : true,
   "IPAddress" : "10.11.12.87",
   "MACAddress" : "78:3E:53:69:F8:82",
   "activeStandby" : true,
   "airplayID" : "Sky Q Conservatory",
   "btID" : "Sky Q Mini0149",
   "cable" : false,
   "deviceID" : "32D0010487030149",
   "estVersion" : "EST 3a",
   "gateway" : false,
   "gatewayIPAddress" : "10.11.12.174",
   "hardwareName" : "MR BOX",
   "hdrCapable" : false,
   "householdToken" : "",
   "localIRDatabase" : true,
   "manufacturer" : "Sky",
   "meshEnabled" : true,
   "modelNumber" : "Q071.000.29.00L (4x4gj4k)",
   "networkVersion" : "2.00",
   "numDTTTuners" : 0,
   "pipCapable" : false,
   "purchasebalance" : "0.01",
   "purchaselimit" : "100.01",
   "receiverID" : "6 194E666501989CD0",
   "serialNumber" : "0487030149 8",
   "showTimeShiftedCategory" : true,
   "systemUptime" : 64984,
   "uhdCapable" : false,
   "versionNumber" : "32D001",
   "vespaID" : "10",
   "viewingCardNumber" : "783986953",
   "wakeReason" : "POWERON"
}

**Comment by Mathy5** [comment]
this is what i see

curl http://192.168.178.30:9006/as/system/information
{
   "ASVersion" : "Q072.000.36.00-AS_12.2.0",
   "DRMActivationStatus" : true,
   "IPAddress" : "192.168.178.30",
   "MACAddress" : "38:A6:CE:42:A5:7A",
   "activeStandby" : true,
   "airplayID" : "Sky Q 2TB Box3426",
   "btID" : "Sky Q 2TB Box3426",
   "cable" : false,
   "chipID" : "265 753 7458 7",
   "deviceID" : "32B1910490323426",
   "estVersion" : "EST 1",
   "gateway" : true,
   "gatewayIPAddress" : "not MR",
   "hardwareName" : "Falcon",
   "hdrCapable" : true,
   "householdToken" : "",
   "localIRDatabase" : true,
   "manufacturer" : "Sky",
   "meshEnabled" : true,
   "modelNumber" : "Q072.000.36.00L (4xaevps)",
   "networkVersion" : "2.00",
   "numDTTTuners" : 4,
   "pipCapable" : true,
   "purchasebalance" : "0.01",
   "purchaselimit" : "17.01",
   "receiverID" : "9 1E66CDB20131D0AC",
   "serialNumber" : "0490323926 1",
   "showTimeShiftedCategory" : false,
   "subscriberID" : "1493337",
   "systemUptime" : 22014,
   "uhdCapable" : true,
   "versionNumber" : "32B191",
   "viewingCardNumber" : "422210915",
   "wakeReason" : "ECO"
}

**Comment by jdebardi** [comment]
Hmmm, not sure then! What if you nmap the box IP, which ports are open?

You should find 49160 is open (which is the one the remote commands are sent to).

There is a chance yours is using 5900 still (which was used in firmware before v060 here), but I doubt it as you are on v072.

As you are in Italy your firmware is different versions to the 'known working' ones here in the UK and the different port problems etc.

**Comment by jdebardi** [comment]
Also - please paste your home bridge config (or at least the section for the Sky Q box)

**Comment by Mathy5** [comment]
![p](https://user-images.githubusercontent.com/35546499/44779471-d8b90300-ab7f-11e8-9554-4c4d47089bed.jpeg)

Maybe i made a mistake here, new in this kind of stuff... all my others `platforms` works perfectly

        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "031-45-154"
        },
        "accessories": [{
                "accessory": "SkyQ",
                "name": "Sky Q Box",
                "ipAddress": "<192.168.178.30>"
        }],

**Comment by jdebardi** [comment]
Yep, remove the <> brackets around the IP and it should all work 👍

**Comment by Mathy5** [comment]
@jdebardi Jezus i feel so retarded sorry! Thanks A LOT!
Can i mange to do some stuff like change channels etc with homekit or just power on/off (i'm very happy just with that) but you know, it will be cool to say "hei siry change the channel to..."

**Comment by jdebardi** [comment]
I have my own branch which supports what you want here 
https://github.com/jdebardi/homebridge-sky-q/blob/Any-Cmd/README.md

To install it, override your version of /usr/lib/node_modules/homebridge-sky-q/index.js with the one in my Any-Cmd branch. I'm assuming your node_modules path is in /usr/lib!

**Comment by jdebardi** [comment]
Given a few of us have been using the any-cmd with success for 6-7 months now, I've requested it be pulled back into this master version so it becomes the default installed one via npm.

**Comment by Mathy5** [comment]
@jdebardi great! because i'm not finding "homebridge-sky-q" only got "homebridge-sky-q-control" but nevermind, for now on/off via Siri is cool enough.

**Comment by jdebardi** [comment]
You have installed a fork of this package by someone else. I suggest you npm uninstall that fork and install this one (i.e. remove homebridge-sky-q-control and install homebridge-sky-q).
Look at the homebridge-sky-q-control it is not as powerful or elegant as mine ;)

**Comment by jdebardi** [comment]
FYI, Adam as merged my any-cmd already, so if you remove homebridge-sky-q-control and install homebridge-sky-q you will have all the features without needing to manually override the index.js 👍
